### --------------------------------------------------------
### API DI AUTENTICAZIONE
### --------------------------------------------------------

### Effettua il login come utente di test
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "email": "test@polito.it",
  "password": "password"
}

### Verifica la sessione corrente
GET http://localhost:3001/api/sessions/current

### --------------------------------------------------------
### API DI GIOCO (Richiedono Autenticazione)
### --------------------------------------------------------

### Avvia una nuova partita (deve restituire 2 stazioni distanti almeno 3 fermate)
POST http://localhost:3001/api/games/start

### Esegui l'intero percorso calcolato in un solo colpo 
### (ATTENZIONE: Modifica l'array "route" con gli ID stazione validi dalla tua partenza alla tua destinazione)
POST http://localhost:3001/api/games/execute
Content-Type: application/json

{
  "route": [4, 6, 10]
}

### --------------------------------------------------------
### API DELLE STATISTICHE
### --------------------------------------------------------

### Recupera lo storico delle partite dell'utente loggato
GET http://localhost:3001/api/users/history

### Recupera la classifica generale (Highscore di ogni utente)
GET http://localhost:3001/api/games/ranking

### --------------------------------------------------------
### LOGOUT & TEST DI SICUREZZA
### --------------------------------------------------------

### Effettua il logout
DELETE http://localhost:3001/api/sessions/current

### Test Sicurezza: Prova ad avviare una partita da Visitatore (Deve fallire con 401 Unauthorized)
POST  http://localhost:3001/api/games/start

### Test Sicurezza: Prova ad inviare un percorso da Visitatore (Deve fallire con 401 Unauthorized)
POST http://localhost:3001/api/games/execute
Content-Type: application/json

{
  "route": [2, 5, 8]
}